[build]
target = "./armv7a-vex-v5.json"

[target.wasm32-unknown-unknown]
rustflags = ["-Clink-arg=--export-memory", "-Clink-arg=--import-table"]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[env]
CC = "clang"
CXX = "clang++"
GCC_ARM_TOOLCHAIN = "/opt/homebrew/opt/arm-gcc-bin@14"
