[build]
target = "./armv7a-vex-v5.json"

[target.wasm32-unknown-unknown]
rustflags = ["-Clink-arg=--export-memory", "-Clink-arg=--import-table"]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[env]
CMAKE_GENERATOR = "Ninja"
CC = "clang"
CXX = "clang++"

# Change based on operating system - path to ARM Embedded Toolchain
# GCC_ARM_TOOLCHAIN = "/opt/homebrew/opt/arm-gcc-bin@14"
#GCC_ARM_TOOLCHAIN = "C:\\Program Files (x86)\\Arm GNU Toolchain arm-none-eabi\\14.2 rel1"
GCC_ARM_TOOLCHAIN = { relative = true, value = "../sysroot" }

