name: Build

on: [push, pull_request]

jobs:
    check:
        name: Check
        runs-on: ubuntu-latest
        steps:
            - name: Setup | Checkout
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Setup | Toolchain
              uses: dtolnay/rust-toolchain@master
              with:
                  toolchain: nightly-2025-02-18
                  components: rust-src

            - name: Setup Ninja
              uses: ashutoshvarma/setup-ninja@v1.1
              with:
                version: '1.12.1'

            - name: Check
              run: cargo check
